const DATABASE_NAME = "local-do-rush-rxdb";
const DEFAULT_RECENT_LIMIT = 20;
const DEFAULT_CONTEXT_ENTRIES = 5;
const DEFAULT_JOB_PRIORITY = 3;
const DEFAULT_MAX_ATTEMPTS = 5;

export { DATABASE_NAME, DEFAULT_RECENT_LIMIT, DEFAULT_CONTEXT_ENTRIES, DEFAULT_JOB_PRIORITY, DEFAULT_MAX_ATTEMPTS };